name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Display where are we
        run: pwd
        shell: bash

      - name: Display files
        run: ls -lahR
        shell: bash

      - name: Link Checker
        uses: peter-evans/link-checker@v1.2.0
        with:
          args: -v -r *

      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: "."
