name: Linters

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.3
      with:
        root: "."
        format: text
        log_level: WARNING
        css: true
